name: CI

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install Parent Folder
        run: npm install
      - name: Run linting
        run: npm run lint

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install Parent Folder
        run: npm install
      - name: Ensure no package-lock.json changes
        run: git diff --exit-code
      - name: Build
        run: npm run build

 